### ISSUE TITLE
Image wrong

### ISSUE THREAD

**Issue by vanduc95** [cloudcomputinghust/openstack-manual#20]
@Monlight hình minh họa ở bước 2 và bước 4 trong phần "Bài toán chuyển gói tin trong 2 mạng Lan khác nhau" bị nhầm rồi, vào sửa lại nhé.

**Comment by sunlu1996** [comment]
@vanduc95 Anh ơi em sửa lại rồi, em thêm trình tự cho nó ạ, anh review lại hộ em xem em nhé

**Comment by vanduc95** [comment]
ok đấy em, pull request lên nhé.
